### ISSUE TITLE
Integrate fsa-prototype-kit into ref-app-inspections

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/ref-app-inspections#16]
## Summary

Now that the Webpack/Handlebars-based Prototype Kit has reached a minimally stable state, let's get it running with this project. This will also serve to at least "prove" the Prototype Kit and then mature it.

## Background

@francisrupert had started initial prototyping of the overall template and a exploratory design of "Inspections List". It's currently purely static HTML with no tooling.

You'll be able to just view it locally out of `src`, or view it on [Sharepoint](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/XCut%20-%20UX/8.%20Projects/Reference%20Apps/Inspections/04%20design/prototype/ref-app-inspections/MASTER/index.html).

## Tasking

- [x] Create a branch and integrate. 
- [x] Make sure all `fsa-style` assets and tooling works correctly.
- [x] Create the most basic level of HBS partials. You'll see comments throughout where a starter set of partials should start and end (example is listed at the bottom of this comment).
- [x] Test out very basic level of passing parameters
- [x] Test out nesting partials
- [x] Test out very very _very_ basic HBS logic, e.g. `{{#if foo }}yup{{else}}nope{{/if}}`
- [ ] Eventually (though very very low priority), we can explore things like stubbing out a bunch of context data in a `file.json` or something. Fun to use, but bottom of the list.

(Feel free to edit this Task List to be more relevant to what makes sense.)

### Partial start/end example
https://github.com/USDA-FSA/ref-app-inspections/blob/a4513119000fbf0eac9296d3eb50d84bed1bb320/src/index.html#L34-L37

**Comment by bignamehere** [comment]
@francisrupert because there currently is no way to perform any advanced functionality using Handlebars, such as passing or variables, I am implementing the native Webpack version, which just uses .html files. If we are successful at enabling more advanced features, it shouldn't be too much of a lift to update the project with Handlebars.

**Comment by francisrupert** [comment]
@bignamehere

Hmm, yesterday I was able to do it off your Handlebars branch. I should have published it as a branch so you can see it. 

eg `{{> component title=“sup” }}`

**Comment by bignamehere** [comment]
@francisrupert Yes, you can pass a variable at the point of HTML Partial inclusion, but that doesn't add much lift at all. What is currently failing in the Handlebars feature branch is being able to pass data (JSON) at the point of JavaScript object creation. (see code below)

var baseTemplate = require('./includes/base.hbs');

document.addEventListener("DOMContentLoaded", function() {
  
  baseTemplate(
    { 
      pageTitle: "Handlebars Template",
      pageHeader: "Baseline Handlebars Application"
    }
  );
  
  //document.body.appendChild( newNode );
});

baseTemplate is supposed to be an object with a native function where you can pass it JSON data that can later be used. So this should mean that in base.hbs the pageTitle and pageHeader should be available for consumption.  So in base.hbs the code below should output "Baseline Handlebars Template" in the Header text, but it doesn't. Not sure why.

`<h1>{{ pageHeader }}</h1>`

What I was hoping to be able to do with the FSA Prototype Kit is to be able to have JSON be loaded in the application at the point of `index.js` which is where the data above would be injected into the base.hbs and anything that extends base.hbs would also have that JSON data available (in theory). Because most, if not all, of the examples of Templating engines online utilize vanilla javascript to implement, and not Webpack, it has proven very challenging to find a way to pass data. I feel like Handlebars would be valuable if we were able to do this, but from the research I have done, I don't see a way to complete what we are looking to do (yet).

With that all said, I am not sure if there is a benefit to including these Handlebar features, when they don't add much value. From a Prototype Kit perspective, it also doesn't make too much sense to have the project be dependent on yet another framework, when Webpack alone can perform HTML Partials inclusion. Wouldn't it be better to keep the Prototype Kit as "baseline" as possible, so that it can be forked and the Designer/Developer can choose the Templating engine they want, or go without it?

**Comment by francisrupert** [comment]
@bignamehere,

My Handlebars/Webpack exploration is at [experimental/france-handlebars-play](https://github.com/USDA-FSA/fsa-prototype-kit/tree/experimental/france-handlebars-play).

![localhost_8888_](https://user-images.githubusercontent.com/1165933/44051212-d7220aec-9efe-11e8-8124-759f4a5a5f0f.png)

**Comment by bignamehere** [comment]
Assigning to @francisrupert to review project. Please comment and assign back when done.

**Comment by bignamehere** [comment]
@francisrupert  I was able to add in the capability to use a JSON file to add pages to the webpack config. It helps to keep the webpack.common.js a bit cleaner.

**Comment by francisrupert** [comment]
@bignamehere,

Cool, still feels odd to have to manually declare them, still better than before. There's got to be a way to just do  _"each *`.hbs` in `/pages/` directory."_ 

Let's powwow on overall review of the Handlebars approach when I'm back from my PCP consult (1:15pm-2:30pm).

**Comment by bignamehere** [comment]
Closing as per our meeting and conversations. I will create more specific Issues related to the TO DO items that came from our meeting.
